# Generated by Django 4.2.11 on 2024-03-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_itemdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='itemsid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.items'),
        ),
    ]
